### ISSUE TITLE
Roadmap for this Project

### ISSUE THREAD

**Issue by LakshyaKhatri** [LakshyaKhatri/Crime-Count-Bot#5]
Here's a basic roadmap for this project:

SLC (Simple Lovable Complete)
---
 - [ ] Create a hello world bot and test it locally
 - [ ] Write some basic tests and set up a CI pipeline
 - [ ] Create a docker image and deploy it on Azure
 - [ ] Set up a CD pipeline

Growing The Project
---
- [ ] Update this section for more things
